# Generated by Django 3.2.6 on 2021-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_remove_categories_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='url_slug',
        ),
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
