# Generated by Django 3.2.6 on 2021-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_auto_20210828_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
