# Generated by Django 3.2 on 2021-08-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20210829_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
