# Generated by Django 3.2 on 2021-08-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_subcategories_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_long_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='url_slug',
        ),
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(default='https://m.media-amazon.com/images/I/71hPjliac6S._AC_SL1500_.jpg'),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
