# Generated by Django 3.2.6 on 2021-09-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_auto_20210901_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='added_by_merchant',
        ),
    ]
