# Generated by Django 3.2.6 on 2021-09-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_remove_products_added_by_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.subcategories', verbose_name='category'),
        ),
    ]
